config:
  backup: true
  create: true
  dotpath: dotfiles-user
dotfiles:
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_fish_plugins:
    src: config/fish/fish_plugins
    dst: ~/.config/fish/fish_plugins
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_micro:
    src: config/micro
    dst: ~/.config/micro
  d_conky:
    src: config/conky
    dst: ~/.config/conky
  f_vivaldi-stable.conf:
    src: config/vivaldi-stable.conf
    dst: ~/.config/vivaldi-stable.conf
  f_ssh-agent.service:
    src: config/systemd/user/ssh-agent.service
    dst: ~/.config/systemd/user/ssh-agent.service
  f_ssh-add.desktop:
    src: config/autostart/ssh-add.desktop
    dst: ~/.config/autostart/ssh-add.desktop
profiles:
  mac.local:
    dotfiles:
    - f_config.fish
    - f_fish_plugins
    - d_kitty
    - d_micro
  nh5zen:
    dotfiles:
    - f_config.fish
    - f_fish_plugins
    - d_kitty
    - d_micro
    - d_conky
    - f_vivaldi-stable.conf
    - f_ssh-agent.service
    - f_ssh-add.desktop
